Added Hill-Type Muscle Simulation
modenaxe/awesome-biomechanics pull request #151
Opened 2023-10-30 08:23 UTC by haripen

2023-12-08 02:10 UTC, modenaxe requested changes
@haripen thank you for your contribution! I have spotted a small issue in the description...if you fix that I will approve the merge...thank you!

2023-12-08 02:10 UTC, modenaxe commented on README.md
Please fix "The version with (Matlab) and without (Matlab, Python)" to "The version with (Matlab) and without Matlab, (Python)"

2023-12-14 19:44 UTC, haripen commented
@modenaxe Thanks for pointing out the confusing wording. I've now completely removed the Matlab and Python references and moved the brackets regarding the knee:
"KneeExt provides simulation models for studying muscle behavior during dynamic knee extensions (knee approximated as hinge joint). The versions with and without elasticities can be used for non-linear parameter identification to determine neuromuscular properties non-invasively and in vivo from kinetic and kinematic data."

2023-12-17 23:33 UTC, modenaxe approved these changes

2023-12-17 23:33 UTC, merged